version: '3'
services:
  timescaledb01:
    container_name: timescaledb01
    image: postgis/postgis:12-3.4	
    # image: timescale/timescaledb:latest-pg12
    # image:  postgres:12.17-bullseye
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: timescaledb
      POSTGRES_PASSWORD: password
    networks:
     - db
    volumes:
      - ./resources/timescaledb01/init_gisdb_schema.sh:/docker-entrypoint-initdb.d/init_gisdb_schema.sh

  timescaledb02:
    container_name: timescaledb02
    image: postgis/postgis:12-3.4	
    # image:  postgres:12.17-bullseye
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: timescaledb
      POSTGRES_PASSWORD: password
    networks:
     - db
    volumes:
      - ./resources/timescaledb01/init_gisdb_schema.sh:/docker-entrypoint-initdb.d/init_gisdb_schema.sh



  proxy:
    ## get more versions of proxy here : https://hub.docker.com/r/shardingsphere/sharding-proxy/tags
    image: "apache/shardingsphere-proxy:5.4.1"
    container_name: sharding-sphere-proxy
    depends_on:
     - timescaledb01
     - timescaledb02
    # wait-for-it.sh will make proxy entry point wait until mysql container 3306 port open
    entrypoint: >
     /bin/sh -c " chmod +x /opt/wait-for-it.sh
     &&/opt/wait-for-it.sh timescaledb01:5432 --timeout=60 --strict --
     && sleep 5
     && /opt/shardingsphere-proxy/bin/start.sh 3308
     && tail -f /opt/shardingsphere-proxy/logs/stdout.log"
    ports: 
     - 3308:3308
    networks:
     - db
    volumes:
     - ./conf/:/opt/shardingsphere-proxy/conf
     - ./tools/wait-for-it.sh:/opt/wait-for-it.sh
    environment:
     - JVM_OPTS="-Djava.awt.headless=true"
    
networks:
  db:
    name: db-networks
    # Use a custom driver
    driver: bridge
    ipam:
        driver: default
        config:
            - 
              subnet: 192.168.2.0/24
