version: '3'
services:
  timescaledb:
    container_name: timescaledb01
    image: timescale/timescaledb:latest-pg12
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: timescaledb
      POSTGRES_PASSWORD: password
    networks:
     - db
    # volumes:
    #   - ./resources/timescaledb01/:/docker-entrypoint-initdb.d/


  proxy:
    ## get more versions of proxy here : https://hub.docker.com/r/shardingsphere/sharding-proxy/tags
    image: "shardingsphere/sharding-proxy:3.1.0"
    container_name: sharding-sphere-proxy
    depends_on:
     - timescaledb
    ## wait-for-it.sh will make proxy entry point wait until mysql container 3306 port open
    entrypoint: >
     /bin/sh -c " chmod +x /opt/wait-for-it.sh
     && cp  /opt/sharding-proxy/ext-lib/* /opt/sharding-proxy/lib
     &&/opt/wait-for-it.sh timescaledb01:5432 --timeout=20 --strict --
     && /opt/sharding-proxy/bin/start.sh 3308 
     && tail -f /opt/sharding-proxy/logs/stdout.log"
    ports: 
     - "13308:3308"
    networks:
     - db
    volumes:
     - ./conf/:/opt/sharding-proxy/conf
     - ./tools/wait-for-it.sh:/opt/wait-for-it.sh
     - ./ext-lib:/opt/sharding-proxy/ext-lib
    environment:
     - JVM_OPTS="-Djava.awt.headless=true"
    
networks:
  db:
    name: db-networks
    # Use a custom driver
    driver: bridge
    ipam:
        driver: default
        config:
            - 
              subnet: 192.168.2.0/24
